import type { TaskPriority } from "../../shared/types";
import type { TranslationKey } from "../i18n/translations/en";

/** Human-readable name i18n key per level (P0 = Highest … P4 = Lowest). */
export const PRIORITY_NAME_KEYS: Record<TaskPriority, TranslationKey> = {
	P0: "priority.name.P0",
	P1: "priority.name.P1",
	P2: "priority.name.P2",
	P3: "priority.name.P3",
	P4: "priority.name.P4",
};

/**
 * Semantic-token styling per priority level. NO hardcoded colors — only theme
 * tokens, so both dark and light themes follow automatically (DESIGN.md /
 * AGENTS.md). Design intent: a "heat ramp" by importance — P0 red → P1 orange →
 * P2 yellow → P3 green cool down as urgency drops, and only the lowest level
 * (P4) is chromatically neutral (grey). Built entirely from existing semantic
 * tokens (danger / awake / warning / success / fg-muted) so no palette additions
 * are needed.
 */
export interface PriorityStyle {
	/** Vivid look for the always-on `P{n}` badge (card, picker, detail/create modals). */
	badge: string;
	/** Unselected filter chip: the level's own colour, dimmed — lifts on hover. */
	chipIdle: string;
	/** Selected filter chip: colour lit to full with a matching ring highlight. */
	chipActive: string;
}

// Opacity steps are limited to values the codebase already ships (/10, /15, /30)
// so the utilities are guaranteed present — arbitrary steps like /8, /12 are not
// generated by this project's Tailwind build. Selection is shown by lifting
// opacity + adding a full-colour ring, never by inventing a new step.
export const PRIORITY_STYLES: Record<TaskPriority, PriorityStyle> = {
	P0: {
		badge: "text-danger bg-danger/15 border border-danger/30",
		chipIdle: "text-danger border border-danger/30 opacity-60 hover:opacity-100",
		chipActive: "text-danger bg-danger/15 border border-danger/30 ring-1 ring-danger",
	},
	P1: {
		badge: "text-awake bg-awake/15 border border-awake/30",
		chipIdle: "text-awake border border-awake/30 opacity-60 hover:opacity-100",
		chipActive: "text-awake bg-awake/15 border border-awake/30 ring-1 ring-awake",
	},
	// `warning-paper` is the light-theme-only fill that gives P2 its yellow back:
	// yellow ink does not exist on white paper (see --warning in index.css).
	P2: {
		badge: "warning-paper text-warning-strong bg-warning/15 border border-warning/30",
		chipIdle: "warning-paper text-warning-strong border border-warning/30 opacity-60 hover:opacity-100",
		chipActive: "warning-paper text-warning-strong bg-warning/15 border border-warning/30 ring-1 ring-warning",
	},
	P3: {
		badge: "text-success bg-success/15 border border-success/30",
		chipIdle: "text-success border border-success/30 opacity-60 hover:opacity-100",
		chipActive: "text-success bg-success/15 border border-success/30 ring-1 ring-success",
	},
	P4: {
		badge: "text-fg-3 bg-fg/10 border border-transparent",
		chipIdle: "text-fg-3 border border-edge opacity-60 hover:opacity-100",
		chipActive: "text-fg-3 bg-fg/10 border border-edge ring-1 ring-edge-active",
	},
};
