/**
 * TypeScript lint wrapper.
 *
 * Runs `tsc --noEmit` and reports only errors originating from our `src/`
 * directory. Third-party packages (e.g. electrobun) ship raw `.ts` source
 * files instead of `.d.ts` declarations, so `skipLibCheck` does not suppress
 * their errors. We own only `src/` — errors there must be zero.
 *
 * A tsc run that failed without per-file diagnostics (corrupt tsconfig,
 * missing binary, crash) is a lint failure too — see evaluateTscOutput.
 */

import { evaluateTscOutput } from "../src/bun/lint-tsc-output";

// Ensure build-info.generated.ts exists (it's created during build,
// but in a fresh worktree it won't be there yet).
const buildInfoPath = `${import.meta.dir}/../src/shared/build-info.generated.ts`;
if (!(await Bun.file(buildInfoPath).exists())) {
	const gen = Bun.spawnSync(
		["bun", `${import.meta.dir}/generate-build-info.ts`],
		{ stdout: "inherit", stderr: "inherit", env: process.env },
	);
	if (gen.exitCode !== 0) {
		console.error("Failed to generate build-info.generated.ts");
		process.exit(1);
	}
}

// Ensure changelog-bundled.ts exists (generated by scripts/generate-changelog.ts,
// but in a fresh worktree it won't be there yet).
const changelogBundledPath = `${import.meta.dir}/../src/bun/changelog-bundled.ts`;
if (!(await Bun.file(changelogBundledPath).exists())) {
	const gen = Bun.spawnSync(
		["bun", `${import.meta.dir}/generate-changelog.ts`],
		{ stdout: "inherit", stderr: "inherit", env: process.env },
	);
	if (gen.exitCode !== 0) {
		console.error("Failed to generate changelog-bundled.ts");
		process.exit(1);
	}
}

// `--pretty false` is load-bearing, not cosmetic: tsc auto-enables pretty output
// on a TTY, and a pretty diagnostic reads `file.ts:12:5 - error TS…` instead of
// `file.ts(12,5): error TS…`. evaluateTscOutput cannot recognise the pretty form,
// so ANY third-party error would look like a crash and fail the run locally while
// CI (no TTY, plain output) stayed green.
const result = Bun.spawnSync(["bun", "x", "tsc", "--noEmit", "--pretty", "false"], {
	stdout: "pipe",
	stderr: "pipe",
	env: process.env,
});

const combined = [result.stdout, result.stderr]
	.map((b) => (b ? Buffer.from(b as ArrayBuffer).toString() : ""))
	.join("");

const evaluation = evaluateTscOutput(result.exitCode ?? 1, combined);

if (evaluation.failed) {
	if (evaluation.errorLines.length > 0) {
		process.stderr.write(evaluation.errorLines.join("\n") + "\n");
	} else {
		process.stderr.write(`tsc exited with code ${result.exitCode} and produced no diagnostics\n`);
	}
	process.exit(1);
}

console.log("TypeScript: no errors in src/");
